### ISSUE TITLE
Just an empty directory after `kickstart ...` cmd

### ISSUE THREAD

**Issue by jimmychu0807** [sacha-l/kickstart-substrate#5]
After running:

```bash
kickstart https://github.com/sacha-l/kickstart-substrate
```

I only have an empty `substrate-node-template` directory created.

**Comment by chevdor** [comment]
Hi @jimmychu0807, I think the template will be further improved soon but the issue you reported should be fixed now. You can test the exact same command and it should work now since bf36507c6b372673002b3a2f3f0cce327d46172d. I would suggest to close the issue now and re-open if that still expand to an empty folder.

**Comment by jimmychu0807** [comment]
Cool, issue resolved. Thanks Chevdor and Sacha.
